"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.USERS_SERVICE_EVENTS = void 0;
const USERS_SIGN_UP_EVENTS = {
    USER_SIGN_UP: 'USER_SIGN_UP',
    USER_SIGN_UP_ERROR: 'USER_SIGN_UP_ERROR',
    USER_SIGN_UP_VIA_GOOGLE: 'USER_SIGN_UP_VIA_GOOGLE',
    USER_SIGN_UP_VIA_GOOGLE_ERROR: 'USER_SIGN_UP_VIA_GOOGLE_ERROR',
};
const USERS_SIGN_IN_EVENTS = {
    USER_SIGN_IN: 'USER_SIGN_IN',
    USER_SIGN_IN_ERROR: 'USER_SIGN_IN_ERROR',
    USER_SIGN_IN_VIA_GOOGLE: 'USER_SIGN_IN_VIA_GOOGLE',
    USER_SIGN_IN_VIA_GOOGLE_ERROR: 'USER_SIGN_IN_VIA_GOOGLE_ERROR',
};
const PERMISSIONS_EVENTS = {
    USER_PERMISSIONS_REQUESTED: 'USER_PERMISSIONS_REQUESTED',
    USER_PERMISSIONS_APPROVED: 'USER_PERMISSIONS_APPROVED',
};
const CHANGE_PASSWORD_EVENTS = {
    RESET_PASSWORD_REQUESTED: 'RESET_PASSWORD_REQUESTED',
};
exports.USERS_SERVICE_EVENTS = {
    ...USERS_SIGN_UP_EVENTS,
    ...USERS_SIGN_IN_EVENTS,
    ...PERMISSIONS_EVENTS,
    ...CHANGE_PASSWORD_EVENTS,
};
//# sourceMappingURL=users-service.events.js.map