import * as assert from 'assert'
import { factory } from '../../../src/adapters/factories'
import { ConfigService } from '../../../src/services/config.service'
import { dropDatabase } from '../../util/mongodb-util'
import { getConfig } from '../../util/settings'
import { before } from 'mocha'
import { initVerifyToken } from '../../../src'
import { IConfig } from '../../../src/interfaces'
import { ACTIVATE_USER_BY } from '../../../src/constant'

// public/private keys generated by:
// ssh-keygen -t rsa -b 1024 -m PEM -f authenzify-test-key
// ssh-keygen -f authenzify-test-key -e -m PKCS8 > authenzify-test-key.pub

describe('Sign In', () => {
  let usersManagements

  let config: IConfig
  const { USER_EMAIL, USER_PASSWORD } = process.env
  const credentials = { email: USER_EMAIL, password: USER_PASSWORD }

  before(async () => {
    config = await getConfig()
    const storageConfig = config.storage
    await dropDatabase(storageConfig)
    const configService = new ConfigService(config)

    usersManagements = await factory(configService)
    await usersManagements.signUp({
      ...credentials,
      firstName: 'John',
      lastName: 'Doe',
    })
  })

  describe(`Verify user by '${ACTIVATE_USER_BY.AUTO}'`, () => {
    it('Should test Users.signIn verify token', async () => {
      const token = await usersManagements.signIn(credentials)
      const { verifyToken } = initVerifyToken({
        publicKey: config.publicKey,
        jwtOptions: config.jwtOptions,
      })
      const encoded = verifyToken(token)
      assert.equal(encoded.email, credentials.email)
    })
  })
})
