import { decode } from 'jsonwebtoken'
import * as assert from 'assert'
import { factory } from '../../../src/adapters/factories'
import { ConfigService } from '../../../src/services/config.service'
import { dropDatabase } from '../../util/mongodb-util'
import { getConfig } from '../../util/settings'
import { before } from 'mocha'
import { ACTIVATE_USER_BY } from '../../../src/constant'

// public/private keys generated by:
// ssh-keygen -t rsa -b 1024 -m PEM -f authenzify-test-key
// ssh-keygen -f authenzify-test-key -e -m PKCS8 > authenzify-test-key.pub

describe('Sign In', () => {
  let usersManagement
  const credentials = { email: 'haim@domain.com', password: '1@Ea5S' }

  before(async () => {
    const config = await getConfig()
    await dropDatabase(config.uri)
    const configService = new ConfigService(config)

    usersManagement = await factory(configService)

    await usersManagement.signUp({
      ...credentials,
      firstName: 'John',
      lastName: 'Doe',
    })
  })

  describe(`Verify user by '${ACTIVATE_USER_BY.AUTO}'`, () => {
    it('Should test Users.signIn decode JWT token is valid', async () => {
      const token = await usersManagement.signIn(credentials)
      const decoded = decode(token)
      assert.equal(decoded.email, credentials.email)
    })
  })
})
