export const VERIFICATION_TYPES = Object.freeze({
  SIGN_UP: 'SIGN_UP',
  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  USER_PERMISSIONS_REQUEST: 'USER_PERMISSIONS_REQUEST',
  DID_NOT_REQUESTED_TO_RESET_PASSWORD: 'DID_NOT_REQUESTED_TO_RESET_PASSWORD',
})

export const EmailProvider = {
  NODEMAILER: 'nodemailer',
}

export const ACTIVATE_USER_BY = {
  AUTO: 'AUTO',
  USER_EMAIL: 'USER_EMAIL',
  ADMIN_EMAIL: 'ADMIN_EMAIL',
  CODE: 'CODE',
}

export const USER_SIGNED_UP_OR_IN_BY = Object.freeze({
  EMAIL: 'EMAIL',
  GOOGLE: 'GOOGLE',
})
