export const VERIFICATION_TYPES = Object.freeze({
  SIGN_UP: 'SIGN_UP',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  USER_PERMISSIONS_REQUEST: 'USER_PERMISSIONS_REQUEST',
})

export const EmailProvider = {
  NODEMAILER: 'nodemailer',
}

export const ACTIVATE_USER_BY = {
  AUTO: 'AUTO',
  USER_EMAIL: 'USER_EMAIL',
  ADMIN_EMAIL: 'ADMIN_EMAIL',
  CODE: 'CODE',
}
